---
title: "DARL Project Status Notebook Template"
author: "Thomas Shweh"
date: "25 September 2020"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
subtitle: "Covid Twitter"
---

## Weekly Work Summary	

* RCS ID: shweht
* Project Name: Covid Twitter

  * Weekend (10/43-10/04)
    * Investigate 'quote tweets' within our original tweet analysis pipeline in twitter.Rmd. 
    * These are tweets in which someone retweets a tweet and makes a reply as well.
  * Tuesday (09/22)
    * After Monday standup meeting I shifted my focus on retrieving quote tweets directly from Elasticsearch.
    * No Kibana access meant that I had to manually make requests to the API to find out data about the schema of each document
    * This took up the bulk of my Time
  * Wednesday (09/23)
    * Colaborated with Brandon on working on the reply tweet script.
    * I wrote the portion involving grabbing tweets from Elasticsearch while filtering for a certain status
  * Thursday (09/23)
    * Worked on script for iterating over all results of an Elasticsearch query. Right now it is set to 10 results as a response per query
      
    
* Summary of github commits 

    * For some reason I still cannot push branches to the public github
    * You can see my commit here in my forked repo: https://github.com/shwehtom89/COVID-Twitter/commit/5f9f5a17a7575cbfbd8419c3e69f0849d4a33037
    * This commit focuses on retrieving results from elasticsearch given a certain filter. Right now it is configured to filter for tweets that are replies to other tweets but can be configured to just filter on quote tweets
    * This commit also includes modifying a parameter in our analysis pipeline to retrieve the quoted status of a tweet. More details about this below.

* List of references (if necessary)

    * https://kb.objectrocket.com/elasticsearch/elasticsearch-and-scroll-in-python-953 This is the reasource I used to work with elasticsearch in python
    
      
* Indicate any use of group shared code base

    * I modified twitter.Rmd, our twitter analysis pipeline to experiment with retrieving a tweet's quoted status
    * I worked on https://github.com/TheRensselaerIDEA/COVID-Twitter/blob/sigoub/twitter-api/tools/twitter-api/get-tweets.py
    
* Indicate which parts of your described work were done by you or as part of joint efforts

    * https://github.com/TheRensselaerIDEA/COVID-Twitter/pull/36. 
    * I worked in conjunction with Brandon on his PR on retriving reply response pairs. Brandon was responsible for working and interfacing with the twitter API. He worked on extracting the text from a tweet
    * I worked on interfacing with elasticsearch, finding the index and being able to make a filterd search

## Personal Contribution	

* This week I investigated using quotetweets with our analysis pipeline and adding this dimension of data into the pipeline. I stopped this processes because I found some issues discussed in Primary Findings
* I investigated our elasticsearch indecies and found out how to search both quote tweets and tweets that are in reply to another tweet
* I applied for a Twitter Developer account as well. Brandon found out that he is limited 500,000 API invocations of getting tweets. We will use my account if we run out.
* I updated the script to scroll through the results of an elasticsearch query so we can paginate through all data

## Discussion of Primary Findings 	

* Discuss primary findings:

1. When I attempted to use the existing pipeline to find quote tweets, I was sucessful in getting the quoted status field retrieved from the pipeline. However there were several issues that I saw from this conclusion. For one out of all tweets that we ran the sampling on, only a few of the tweets actually were quote tweets. We could alter the code in Elasticsearch.R to handle filtering for specific fields to circumvent this issue, but that involves restructuring a bit of the existing code support this feature. Another issue that I had with this approach is that the pipeline should be run against a dataset of both quote and reply tweets. This is a better representation of our problem since our data set will not only involved quote tweets but also tweets that are in reply to another. The original plan was to export quote tweets along with the cluster that they belonged to. But this clustering only makes sense in context of the data set that we are using. The current clustering is in relation to all tweets while we want to cluster a data set of reply and response. Another issue with this approach is modifying the pipeline to support an additional data column to represent which tweet the current tweet is responding to. I believe that this is an issue that needed further discussion before going ahead and implementing so that is why I held off of exporting quote tweets from our pipeline. Instead, I chose to gather tweets directly into elasticsearch

2. Filtering tweets by quote and reply. This week I directed my focus to supporting Brandon and writing a script to interface with elasticsearch to gather certain types of tweets. Quoted tweets are denoted by a certain parameter called **quoted_status**. This is an object that will contain tweet data for the parent tweet that the current one is retweeting and responding to. While tweets that are in direct response to another tweet will have the field **in_reply_to_status_id_str** be non null. As a result I was able to make queries against our elasticsearch cluster using the following filter
```
search_param = {
    "_source": True,
    "query": {
      "constant_score" : {
           "filter" : {
              "exists" : {
                 "field" : "in_reply_to_status_id_str"
              }
           }
      }
    }
  }
```
This allows us to search by fields that are non null which allows to located tweets that we are interested in. 

3. Elasticsearch functions closely to a database for retrieving large amounts of data. Currently with the way my query is being configured, I am only getting 10 results from our elasticsearch cluster. On one hand we can change this number to be arbitrarily large, but I am interested in processes all the data. Now I am using what is called elasticsearch's scroll feature to paginate over all the data. This functions much like a database's cursor tools in order to fetch large amounts of data. The part of my code that handles this can be found https://github.com/shwehtom89/COVID-Twitter/blob/quotetweets/tools/gather_tweets.py#L47-L52.

4. Now that we can gather tweets from elasticsearch and from the twitter API there is a need to discuss the schema for how we are going format our data in our new index. This is necessary for us differentiate quote tweets and reply tweets. Since reply tweets are not something that the twitter api returns and somethinge we processes ourselves we need to define this format. We also need to consider fields we are feeding into our data model.

    
## Next Steps

* For the next week I will research how to build R shiny applications and how they work. This will help me build off of the previous work done over the summer and provide useful visualtions
* I will also reasearch language models in order to tackle perdicting response sentiment to a tweet
* Lastly I will familiarize myself with elastic search and be able request tweets and their corresponding replies to gather data for this model
* Configure the script to be searchable, so we can focus on WHO quotetweets and responses
