```{r setup, include=FALSE}
# Required R package installation:
# These will install packages if they are not already installed
# Set the correct default repository
r = getOption("repos")
r["CRAN"] = "http://cran.rstudio.com"
options(repos = r)


if (!require("knitr")) {
  install.packages("knitr")
  library(knitr)
}

if (!require("kableExtra")) {
  install.packages("kableExtra")
  library(kableExtra)
}

knitr::opts_chunk$set(echo = TRUE)

source("Elasticsearch.R")
```

### Configure the search query here:

```{r}
# number of results to return (to return all results, set to NA)
resultsize <- 0

# raw JSON elasticsearch query
query <- '{
  "_source": false,
  "query": {
    "bool": {
      "filter": [
        {
          "simple_query_string": {
            "fields": [
              "place.country_code"
            ],
            "query": "US"
          }
        },
        {
          "simple_query_string": {
            "fields": [
              "place.place_type"
            ],
            "query": "admin city"
          }
        }
      ]
    }
  },
  "aggs": {
    "weekly": {
      "date_histogram": {
        "field": "created_at",
        "calendar_interval": "week",
        "format": "MM/dd/yyyy"
      },
      "aggs": {
        "sentiment_stats": {
          "extended_stats": {
            "field": "sentiment.vader.primary"
          }
        }
      }
    },
    "by_state": {
      "terms": {
        "field": "normalized_state.keyword", 
        "order": {
          "_key": "asc"
        },
        "size": 100
      },
      "aggs": {
        "sentiment_stats": {
          "extended_stats": {
            "field": "sentiment.vader.primary"
          }
        }
      }
    },
    "weekly_by_state": {
      "date_histogram": {
        "field": "created_at",
        "calendar_interval": "week",
        "format": "MM/dd/yyyy"
      },
      "aggs": {
        "by_state": {
          "terms": {
            "field": "normalized_state.keyword",
            "order": {
              "_key": "asc"
            },
            "size": 100
          },
          "aggs": {
            "sentiment_stats": {
              "extended_stats": {
                "field": "sentiment.vader.primary"
              }
            }
          }
        }
      }
    }
  }
}'
```

### Results:

```{r, echo=FALSE}
results <- do_search_raw(indexname="coronavirus-data-masks", 
                     query,
                     resultsize=resultsize,
                     elasticsearch_host="",
                     elasticsearch_path="elasticsearch",
                     elasticsearch_port=443,
                     elasticsearch_schema="https")

#print results
counts.df <- data.frame(results.count=paste(nrow(results$hits$hits), "/", results$hits$total$value))
kable(counts.df) %>% kable_styling()

hits.df <- results$hits$hits
kable(hits.df) %>% kable_styling()

buckets.df <- results$aggregations$by_state$buckets
kable(buckets.df) %>% kable_styling()
```